name: Gradle Build

on:
  push:
    branches: [master]
    paths:
      - 'src/**'
      - '*.kts'
      - '*.properties'
      - '.github/workflows/*.yml'
  pull_request:
    branches: [master]
    paths:
      - 'src/**'
      - '*.kts'
      - '*.properties'
      - '.github/workflows/*.yml'

jobs:

  build:

    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: shadowJar
          gradle-version: wrapper

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: jar
          path: build/libs/**/*.jar
